### ISSUE TITLE
建议去掉渐显/渐隐

### ISSUE THREAD

**Issue by qnnnnez** [lzm956902416/SMT#2]
影响阅读，而且代价昂贵
而图片可以用lazyload

**Comment by brendan-lee** [comment]
没看错的话，邮件回复没成功？
渐显渐隐的问题值得考虑
之前确实不知道lazyload（_/∇＼_）

**Comment by qnnnnez** [comment]
用Edge看着有点不流畅

**Comment by brendan-lee** [comment]
已经在ie里见识过惨不忍睹了= =
